### PR TITLE
Ubuntu Xenial tweak

### PR DESCRIPTION
**Pull request by minakitty**
libtiff4-dev was not an available package in Ubuntu Xenial, but libtiff5-dev is.  Installing it allowed the project to 'make' properly, even though I haven't used TIFF functions, though, so if I'm mistaken on something feel free to shoot it down.

### CODE REVIEW

**Comment by chuckremes** [comment]
This is how I built on Ubuntu 16.10. It crashes but I don't think it's related to this change. :)

**Comment by sglass68** [comment]
Can you update this with just the INSTALL changes please?

**Comment by minakitty** [comment]
I'm really confused, and admittedly not very experienced with github.  I only edited two lines in INSTALL.  I have no idea where these conflicts are coming from or how to resolve them.  Should I just close the PR, reclone the repo and make my edits again?

**Comment by chuckremes** [comment]
@minakitty Google around for how to "rebase" your repository. You have conflicts because the repository owner made changes *AFTER* you forked it. So you need to pull these latest changes into your fork and fix any conflicts. Then the merge will be clean.

The steps to do this are covered pretty well by lots of blogs, stackoverflow.com, etc.

**Comment by sglass68** [comment]
The conflicts are because I rebased master. Normally it would be stable, but since I am still finding problems, I wanted to fix them in the original commit. That way I can bisect easily to find other problems in future.

So you can either do the change again, or fiddle with this one to resolve the conflict in INSTALL and drop changes to the other files.

I have one more set of bugs to figure out (with another dialog) but after that master should be stable.

**Comment by minakitty** [comment]
I never used the command line github, which at this point I think would make rebasing my version against the master problematic, and the website is unable to rebase for me (either I'm doing it wrong or there's just too many changes.  So I'll close this out and reclone after the latest change to master is done.  By chance, do we have some sort of an ETA on that?

**Comment by sglass68** [comment]
OK I have fixed up the remaining QT errors, so don't expect to rebase again (no promises though!) Please go ahead and try your change again.

**Comment by minakitty** [comment]
Done.  New PR is #13

**Pull request closed without merging**
